<a href="https://colab.research.google.com/github/Spencer272/Comandos_en_R/blob/main/Comandos_en_R_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
(3 + exp(2)) / sin(pi)

[1] 8.483308e+16

In [ ]:
round(1789.1234, digits = 3)

[1] 1789.123

In [21]:
x = c(123.4567890, 1.0)
format(x) # using defaults
## [1] "123.4568" " 1.0000"
format(x[1]) # using defaults
## [1] "123.4568"
format(x[2]) # using defaults
## [1] "1"
format(x, digits = 3, nsmall = 1)
## [1] "123.5" " 1.0"
format(x[1], digits = 3, nsmall = 1)
## [1] "123.5"
format(x[2], digits = 3, nsmall = 1)
## [1] "1.0"
format(x, digits = 3, scientific = TRUE)
## [1] "1.23e+02" "1.00e+00"
x = c(123.4567890, 1.0)
sprintf("The numbers are: %4.2f and %.0f", x[1], x[2])
## [1] "The numbers are: 123.46 and 1"
sprintf("The numbers are: %.4g and %.2g", x[1], x[2])
## [1] "The numbers are: 123.5 and 1"
sprintf("The numbers are: %4.2e and %.0e", x[1], x[2])
## [1] "The numbers are: 1.23e+02 and 1e+00"

[1] "123.4568" "  1.0000"

[1] "123.4568"

[1] "1"

[1] "123.5" "  1.0"

[1] "123.5"

[1] "1.0"

[1] "1.23e+02" "1.00e+00"

[1] "The numbers are: 123.46 and 1"

[1] "The numbers are: 123.5 and 1"

[1] "The numbers are: 1.23e+02 and 1e+00"

In [ ]:
a <- letters[1:10]
b <- 1:10
selector <- a > "c"
selector
a[selector]
b[selector]



[1] FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

[1] "d" "e" "f" "g" "h" "i" "j"

[1]  4  5  6  7  8  9 10

[1]  4  5  6  7  8  9 10

[1] "d" "e" "f" "g" "h" "i" "j"

[1]  4  5  6  7  8  9 10

In [22]:
indexes <- which(a > "c")
indexes
a[indexes]
b[indexes]

[1]  4  5  6  7  8  9 10

[1] "d" "e" "f" "g" "h" "i" "j"

[1]  4  5  6  7  8  9 10

In [23]:
A <- matrix(1:20, ncol = 4)
A
one.col.matrix <- matrix(1:6, ncol = 1)
dim(one.col.matrix)
## [1] 6 1
two.col.matrix <- matrix(1:6, ncol = 2)
dim(two.col.matrix)
## [1] 3 2
one.elem.matrix <- matrix(1, ncol = 1)
dim(one.elem.matrix)
## [1] 1 1
no.elem.matrix <- matrix(numeric(), ncol = 0)
dim(no.elem.matrix)
## [1] 0 0

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[1] 6 1

[1] 3 2

[1] 1 1

[1] 0 0

In [ ]:
B <- array(1:27, dim = c(3, 3, 3))
B

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27

In [ ]:
my.vector <- c(1, 1, 0, 0, 0, 1)
my.factor <- factor(x = my.vector, levels = c(1, 0), labels = c("treated", "control"))
my.factor

[1] treated treated control control control treated
Levels: treated control

In [ ]:
my.vector2 <- rep(3:5, 4)
my.vector2
## [1] 3 4 5 3 4 5 3 4 5 3 4 5
my.factor2 <- factor(my.vector2)
my.factor2
## [1] 3 4 5 3 4 5 3 4 5 3 4 5
## Levels: 3 4 5
as.numeric(my.factor2)
## [1] 1 2 3 1 2 3 1 2 3 1 2 3
as.numeric(as.character(my.factor2))
## [1] 3 4 5 3 4 5 3 4 5 3 4 5

[1] 3 4 5 3 4 5 3 4 5 3 4 5

[1] 3 4 5 3 4 5 3 4 5 3 4 5
Levels: 3 4 5

[1] 1 2 3 1 2 3 1 2 3 1 2 3

[1] 3 4 5 3 4 5 3 4 5 3 4 5

In [ ]:
a.list$x
## [1] 1 2 3 4 5 6
a.list[["x"]]
## [1] 1 2 3 4 5 6
a.list[[1]]
## [1] 1 2 3 4 5 6
a.list["x"]
## $x
## [1] 1 2 3 4 5 6
a.list[1]
## $x
## [1] 1 2 3 4 5 6
a.list[c(1,3)]
## $x
## [1] 1 2 3 4 5 6
##
## $z
## [1] TRUE FALSE
try(a.list[[c(1,3)]])
## [1] 3


[1] 1 2 3 4 5 6

[1] 1 2 3 4 5 6

[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$z
[1]  TRUE FALSE

[1] 3

In [ ]:
nested.list <- list(A = list("a", "aa", "aaa"), B = list("b", "bb"))
str(nested.list)
nested.list[2:1]
nested.list[1]
nested.list[[1]][2]
nested.list[[1]][[2]]
nested.list[2]
nested.list[2][[1]]

c.vec <- unlist(nested.list)
c.vec
## A1 A2 A3 B1 B2
## "a" "aa" "aaa" "b" "bb"
is.list(nested.list)
## [1] TRUE
is.list(c.vec)
## [1] FALSE
mode(nested.list)
## [1] "list"
mode(c.vec)
## [1] "character"
names(nested.list)
## [1] "A" "B"
names(c.vec)
## [1] "A1" "A2" "A3" "B1" "B2"

List of 2
 $ A:List of 3
  ..$ : chr "a"
  ..$ : chr "aa"
  ..$ : chr "aaa"
 $ B:List of 2
  ..$ : chr "b"
  ..$ : chr "bb"


$B
$B[[1]]
[1] "b"

$B[[2]]
[1] "bb"


$A
$A[[1]]
[1] "a"

$A[[2]]
[1] "aa"

$A[[3]]
[1] "aaa"

$A
$A[[1]]
[1] "a"

$A[[2]]
[1] "aa"

$A[[3]]
[1] "aaa"

[[1]]
[1] "aa"

[1] "aa"

$B
$B[[1]]
[1] "b"

$B[[2]]
[1] "bb"

[[1]]
[1] "b"

[[2]]
[1] "bb"

A1    A2    A3    B1    B2 
  "a"  "aa" "aaa"   "b"  "bb"

[1] TRUE

[1] FALSE

[1] "list"

[1] "character"

[1] "A" "B"

[1] "A1" "A2" "A3" "B1" "B2"

In [ ]:
a.df <- data.frame(x = 1:6, y = "a", z = c(TRUE, FALSE))
a.df
## x y z
## 1 1 a TRUE
## 2 2 a FALSE
## 3 3 a TRUE
## 4 4 a FALSE
## 5 5 a TRUE
## 6 6 a FALSE
str(a.df)
## 'data.frame': 6 obs. of 3 variables:
## $ x: int 1 2 3 4 5 6
## $ y: chr "a" "a" "a" "a" ...
## $ z: logi TRUE FALSE TRUE FALSE TRUE FALSE
class(a.df)

x y z    
1 1 a  TRUE
2 2 a FALSE
3 3 a  TRUE
4 4 a FALSE
5 5 a  TRUE
6 6 a FALSE

'data.frame':	6 obs. of  3 variables:
 $ x: int  1 2 3 4 5 6
 $ y: chr  "a" "a" "a" "a" ...
 $ z: logi  TRUE FALSE TRUE FALSE TRUE FALSE


[1] "data.frame"